export const metadata = {
  alternates: { canonical: '/terms' },
  title: 'Terms & Conditions — Digital Credit Yield',
  description: 'Terms and conditions for using Digital Credit Yield — an independent tracker for STRC and SATA preferred stocks. Not financial advice.',
};

function Section({ id, title, children }) {
  return (
    <div id={id} className="mb-8">
      <h2 className="text-xl font-semibold mb-3">{title}</h2>
      <div className="text-sm leading-7 space-y-3" style={{ color: 'var(--text-muted)' }}>{children}</div>
    </div>
  );
}

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 sm:px-6 py-12">
      <h1 className="text-3xl font-bold mb-2">Terms & Conditions</h1>
      <p className="text-sm mb-10" style={{ color: 'var(--text-muted)' }}>Last updated: May 2026</p>

      {/* Prominent disclaimer */}
      <div id="disclaimer" className="p-5 rounded-xl mb-10"
        style={{ background: 'rgba(200,137,58,0.08)', border: '2px solid var(--accent-gold)' }}>
        <p className="font-semibold mb-2" style={{ color: 'var(--accent-gold)' }}>Important Disclaimer</p>
        <p className="text-sm leading-6" style={{ color: 'var(--text-primary)' }}>
          This website and its content are for informational and educational purposes only. Nothing on
          this site constitutes financial advice, investment advice, or a solicitation to buy or sell
          any financial instrument. Always seek the advice of a qualified financial adviser before
          making any investment decisions. Past performance is not indicative of future results.
        </p>
      </div>

      <Section title="1. Terms of Use">
        <p>By accessing and using Digital Credit Yield ("the Site"), you accept and agree to be bound by these Terms & Conditions. If you do not agree, please do not use the Site.</p>
        <p>We reserve the right to modify these terms at any time. Continued use of the Site following any changes constitutes your acceptance of the revised terms.</p>
      </Section>

      <Section title="2. Limitation of Liability">
        <p>To the maximum extent permitted by law, Digital Credit Yield and its operators shall not be liable for any direct, indirect, incidental, or consequential damages arising from your use of the Site or reliance on any information presented herein.</p>
        <p>All financial data displayed (prices, yields, distributions) is sourced from third-party providers and may be delayed, inaccurate, or incomplete. We make no representations as to the accuracy, completeness, or timeliness of such data.</p>
        <p>Projections generated by our Growth Projector and Differentiator tools are illustrative models based on user-defined inputs. They do not represent guaranteed returns or predictions of future performance.</p>
        <p>Capital flow data displayed on the Money Flow page is compiled from publicly available SEC 8-K filings. Figures represent gross proceeds as reported at time of filing and may not reflect subsequent adjustments or corrections. We make no representations as to the completeness or accuracy of this data.</p>
      </Section>

      <Section title="3. Intellectual Property">
        <p>All content on this Site — including text, design, graphics, and code — is the property of Digital Credit Yield unless otherwise stated. You may not reproduce, distribute, or create derivative works without prior written consent.</p>
        <p>Financial data sourced from Yahoo Finance is subject to their terms of service. Price and yield charts are rendered using lightweight-charts, an open-source library published by TradingView under the Apache 2.0 licence.</p>
      </Section>

      <Section title="4. Third-Party Links & Services">
        <p>The Site may contain links to third-party websites or use third-party services (including Google Analytics, Google AdSense, and Google Fonts). We are not responsible for the content, accuracy, or practices of any third-party sites or services.</p>
      </Section>

      <Section title="5. Governing Law">
        <p>These Terms & Conditions are governed by and construed in accordance with the laws of England and Wales. Any disputes arising from use of this Site shall be subject to the exclusive jurisdiction of the courts of England and Wales.</p>
      </Section>

      <Section title="6. Contact">
        <p>For questions about these terms, please contact:{' '}
          <a href="mailto:contact@digitalcredityield.com" className="underline" style={{ color: 'var(--accent-gold)' }}>
            contact@digitalcredityield.com
          </a>
        </p>
      </Section>
    </div>
  );
}
