// scripts/quizWatch.js
// Quiz Converter watcher — drop a quiz card image into the "in" folder and this
// renders the 10s animated MP4 and emails it to you, then files the source away.
//
// Run:  node --env-file=.env.local scripts/quizWatch.js
// Drop images into:  ~/QuizConverter/in   (.png .jpg .jpeg)
// Videos are also saved to:  ~/QuizConverter/out
//
// Leave it running in a terminal; it polls every few seconds.

import { Resend } from 'resend';
import { readdir, mkdir, rename, writeFile, stat } from 'fs/promises';
import path from 'path';
import os from 'os';
import { generateQuizVideo } from './quizVideo.js';

const ROOT = path.join(os.homedir(), 'QuizConverter');
const DIR = { in: path.join(ROOT, 'in'), out: path.join(ROOT, 'out'), done: path.join(ROOT, 'done'), failed: path.join(ROOT, 'failed') };
const RECIPIENT = 'robin.gillingham@hotmail.co.uk';
const FROM = 'Digital Credit Yield <contact@digitalcredityield.com>';
const POLL_MS = 3000;
const EXT = new Set(['.png', '.jpg', '.jpeg']);

const seen = new Map();      // filename → last size (to wait for copy to finish)

async function ensureDirs() {
  for (const d of Object.values(DIR)) await mkdir(d, { recursive: true });
}

async function emailVideo(buf, srcName) {
  if (!process.env.RESEND_API_KEY) throw new Error('Missing RESEND_API_KEY (run with --env-file=.env.local)');
  const resend = new Resend(process.env.RESEND_API_KEY);
  const { error } = await resend.emails.send({
    from: FROM,
    to: RECIPIENT,
    subject: `Quiz video — ${srcName}`,
    html: `<div style="font-family:Arial,sans-serif;background:#0a0f1e;color:#e5e7eb;padding:24px;border-radius:12px">
      <p style="margin:0 0 8px">Your quiz card is now a 10-second video — attached as <strong>${srcName.replace(/\.[^.]+$/, '')}.mp4</strong>.</p>
      <p style="margin:0;color:#9ca3af;font-size:13px">Generated by Quiz Converter.</p>
    </div>`,
    attachments: [{ filename: srcName.replace(/\.[^.]+$/, '') + '.mp4', content: buf.toString('base64') }],
  });
  if (error) throw new Error(`Resend error: ${JSON.stringify(error)}`);
}

async function processFile(file) {
  const src = path.join(DIR.in, file);
  const base = file.replace(/\.[^.]+$/, '');
  try {
    console.log(`▶ processing ${file} …`);
    const buf = await generateQuizVideo(src);
    const outPath = path.join(DIR.out, `${base}.mp4`);
    await writeFile(outPath, buf);
    await emailVideo(buf, file);
    await rename(src, path.join(DIR.done, file));
    console.log(`✓ ${file} → ${(buf.length / 1e6).toFixed(2)} MB, emailed to ${RECIPIENT}, saved ${outPath}`);
  } catch (e) {
    console.error(`✗ ${file}: ${e.message}`);
    await rename(src, path.join(DIR.failed, file)).catch(() => {});
  } finally {
    seen.delete(file);
  }
}

// Find the next image that's ready (extension matches, size stable across one
// poll so we don't grab a half-copied file) and process it. One at a time.
async function scan() {
  let files;
  try { files = await readdir(DIR.in); } catch { return; }
  for (const file of files) {
    if (file.startsWith('.')) continue;
    if (!EXT.has(path.extname(file).toLowerCase())) continue;
    let size;
    try { size = (await stat(path.join(DIR.in, file))).size; } catch { continue; }
    if (size > 0 && seen.get(file) === size) {
      seen.delete(file);
      await processFile(file);     // serialise: one render at a time
      return;                      // re-scan fresh next loop
    }
    seen.set(file, size);
  }
}

process.on('unhandledRejection', e => console.error('unhandledRejection:', e));

await ensureDirs();
console.log(`Quiz Converter watching: ${DIR.in}`);
console.log(`Drop .png/.jpg/.jpeg quiz cards there — video is emailed to ${RECIPIENT} and saved to ${DIR.out}`);

// Self-scheduling loop — more robust than setInterval for long blocking renders.
for (;;) {
  try { await scan(); } catch (e) { console.error('scan error:', e.message); }
  await new Promise(r => setTimeout(r, POLL_MS));
}
